site_name: JARVIS Documentation
site_description: Documentation for the JARVIS Voice Assistant
site_author: Jeremy
repo_url: https://github.com/yourusername/jarvis
repo_name: JARVIS

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide:
    - Getting Started: usage/getting-started.md
    - Configuration: usage/configuration.md
    - Voice Commands: usage/voice-commands.md
  - API Reference:
    - Core:
      - JARVIS Core: api/core/jarvis.md
      - Voice Manager: api/core/voice.md
      - NLP Manager: api/core/nlp.md
      - Task Manager: api/core/tasks.md
    - UI:
      - Status Indicator: api/ui/status.md
    - Utils:
      - Exceptions: api/utils/exceptions.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Documentation: development/documentation.md
  - Changelog: changelog.md 