name: Bug Report
description: Create a report to help us improve JARVIS
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of JARVIS are you running?
      placeholder: e.g., 0.1.0
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
      
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.12"
        - "3.11"
        - "3.10"
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
      
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here. 